### ISSUE TITLE
[OpenSubtitle] error: failed to parse TypeError: Cannot read property 'UserPreferedLanguages' of undefined  

### ISSUE THREAD

**Issue by dooniem** [fbacker/docker-opensubtitles#1]
Hi. Not sure if this project is dead or not...But I have not been able to change which languages this container search for.

I see you write that language selection is made from Opensubtitles userprofile. But even though I have English and Swedish selected, I get "Cannot read property 'UserPreferedLanguages' of undefined" in the login-phase and just English is set as language.

I did some experimenting, I edited src/opensubtitle/login.js inside the container, which seems to intentionally ignore langugages set in config? 
I changed: 
`let { languages } = config.opensubtitles;`
into:
`let { languages } = config.opensubtitles.languages;`
re-starting the container my log showed multiple reconnections and receiving the same opensubtitle token over and over. So basically my experimenting failed. Even with just 'languages:"eng"'

Any ideas of what I'm doing wrong?

**Comment by fbacker** [comment]
What happens if you try to set the local config file instead.?

```
{
  "opensubtitles": {
    "username": "...",
    "password": "...",
    "languages": ["eng","swe"]
  }
  ....
}
```

**Comment by fbacker** [comment]
I've also just made an release. Please make sure that you run the latest container and see if that helps.

**Comment by fbacker** [comment]
was able to replicate, another release is made to fix this

**Comment by dooniem** [comment]
Sorry for my late reply. I went with FileBot and found a solution since this didn't work
